# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_question', models.CharField(max_length=200)),
            ],
        ),
    ]
