# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='current_question',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.User'),
        ),
    ]
