# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20160505_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
