# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20160513_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_created',
        ),
        migrations.AddField(
            model_name='user',
            name='represent_id',
            field=models.IntegerField(default=-1),
        ),
    ]
