# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
